#!/bin/bash
#
# LibDOS install script for Linux and MacOS
#
# - builds and copies libdos.a to /usr/local/lib
# - copies all header files to /usr/local/include

LIB=libdos.a
LIBS=/usr/local/lib
LIBDST=$LIBS/$LIB
INCS=/usr/local/include
declare -a headers=("dos.h" "conio.h" "graphics.h")

checkfile () {
    if test -f "$1"; then
        echo "Cannot install: $1 already exists."
        exit 1
    fi
}

make lib

# check if user already has a file with the same name and abort

checkfile $LIBDST
for file in "${headers[@]}"
do
	checkfile $INCS/$file
done

# we're good, copy everything

cp $LIB $LIBS
for file in "${headers[@]}"
do
	cp include/$file $INCS
done

echo "LibDOS was successfully installed."
